name: CI

env:
  PROJECT_NAME: app_calculator 

on:
  push:
    branches: master 
  pull_request:
    branches: master 
    
jobs:
  CodeStyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CheckCode
        uses: andymckay/pycodestyle-action@0.1.3
    
           
     
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: CodeStyle

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

  
    - name: Docker build
      run: docker build -t ${{ secrets.LOGIN_DOCKER }}/$PROJECT_NAME:v$GITHUB_RUN_NUMBER .
      
    - name: Upload to DOCKERHUB    
      run: |
        docker login --username=${{ secrets.LOGIN_DOCKER }} --password=${{ secrets.PASSWORD_DOCKER }}
        docker push ${{ secrets.LOGIN_DOCKER }}/$PROJECT_NAME:v$GITHUB_RUN_NUMBER

