name: CI
env:
  PROJECT_NAME: app_calculator 
on:
  push:
    branches: master 
  pull_request:
    branches: master 
    
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Code Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
        with: 
          args: pycodestyle -v 
            
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker test container
        run: sudo docker build -t $PROJECT_NAME:_Test -f Dockerfile_test . --build-arg .
 
    
  build:
    needs: code-style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Docker build
      run: docker build -t ${{ secrets.LOGIN_DOCKER }}/$PROJECT_NAME:v$GITHUB_RUN_NUMBER .
      
    - name: Upload to DOCKERHUB    
      run: |
        docker login --username=${{ secrets.LOGIN_DOCKER }} --password=${{ secrets.PASSWORD_DOCKER }}
        docker push ${{ secrets.LOGIN_DOCKER }}/$PROJECT_NAME:v$GITHUB_RUN_NUMBER
        
  test:
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker test
      run: docker build -f /Dockerfile_test -t flask_app .
       
#     - name: Docker run flask_app_test
#       run: docker run flask_app_test 
          
 #docker build -f docker/Dockerfile.tst -t flask_app_test .
