name: CI

env:
  PROJECT_NAME: "ekateee/—Åalculator" 

on:
  push:
    branches: master 
  pull_request:
    branches: master 

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
 
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Docker build
      run: |
        docker build -t $PROJECT_NAME:v$GITHUB_RUN_NUMBER .
        docker images
      
#     - name: Upload to DOCKERHUB  
#       run: |
#         # dockerhub
#         docker login --username=${{ secrets.LOGIN_DOCKER }} --password=${{ secrets.PASSWORD_DOCKER }}
#         docker push $PROJECT_NAME:v$GITHUB_RUN_NUMBER

        
 

 

